name: SniperRoyale
version: 1.0
api-version: 1.13
author: TorchNight
main: com.torchnight.sniperroyale.Main

commands:
  sniperroyale:
      usage: /<command>
      description: get sniperroyale commands
      aliases: [sr]